### PR TITLE
feat: add support for animated png output

### PR DESCRIPTION
**Pull request by LinusU**
Very happy to see that the code uses modern libraries and Standard Style, makes it very easy to work with! 👏 👏 

example:

lego-loader

### CODE REVIEW

**Comment by LinusU** [comment]
Potentially it could be nice to output a `.png` file instead `.apng`, while I think that both are valid (at least according to WikiPedia) Finder in macOS will only show an animated preview if the file ends with `.png`.

Either we could always output animated png files, is there a use case where you want only the first frame as a png file? 🤔 or we could have a flag that outputs animated PNGs.

Anyhow, that could easily be done in a follow up PR, just let me know how you want it 💪

**Comment by transitive-bullshit** [comment]
Published as `v1.0.2`.

**Comment by transitive-bullshit** [comment]
Re: `png` vs `apng`, I think a nice follow-up would be to always want to use `png`. If the user supplies an output filename as `png`, then we determine if they want an animated png or a regular png via our `isMultiFrame` regex `/%d|%\d{2,3}d/`.

If the user wants to export the first frame as `png`, maybe we add an additional parameter like `firstFrame: true` to be explicit about this use case?

**Comment by LinusU** [comment]
That sounds great 👍

**Comment by transitive-bullshit** [comment]
Just an fyi I won't have time to get to this for awhile.

**Comment by LinusU** [comment]
No worries, I didn't expect you too either ☺️ 

I was hoping that I would get some time to fix it myself 👍

**Pull request merged**
